# Generated by Django 4.2.24 on 2025-09-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatternCategory',
            new_name='Category',
        ),
    ]
