# Generated by Django 4.2.24 on 2025-09-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_rename_patterncategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
