# Generated by Django 4.2.24 on 2025-10-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_display_name_profile_default_display_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='default_user',
            new_name='user',
        ),
    ]
